# Generated by Django 4.2.7 on 2023-11-28 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('student_id_number', models.CharField(max_length=30)),
                ('birth_place', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('whatsapp_number', models.CharField(max_length=30)),
                ('student_id_card_pic', models.ImageField(blank=True, null=True, upload_to='student_id_card_pics')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('study_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.studyprogram')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
