# Generated by Django 4.2.7 on 2023-12-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='student_id_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
