# Generated by Django 4.2.7 on 2023-12-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
