# Generated by Django 4.2.7 on 2024-02-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userprofile_student_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_fcm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
