# Generated by Django 4.2.7 on 2023-11-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_is_email_confirmed_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
