# Generated by Django 4.2.7 on 2023-12-06 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='study_program',
            new_name='studyprogram',
        ),
    ]
