# Generated by Django 4.2.7 on 2023-11-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_otpcode_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_email_confirmed',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
