# Generated by Django 4.2.7 on 2023-11-29 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_is_email_confirmed_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_profile_id',
            new_name='userprofile_id',
        ),
    ]
