# Generated by Django 4.2.7 on 2024-02-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_token_fcm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_fcm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
