# Generated by Django 4.2.7 on 2024-02-11 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_user_token_fcm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FCMTokens',
            new_name='FCMToken',
        ),
    ]
