# Generated by Django 4.2.7 on 2024-02-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_rename_fcmtokens_fcmtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FCMToken',
        ),
    ]
