version: '3.8'

services:
  uch_backend:
    container_name: uch_backend
    build: 
      context: .
      dockerfile: Dockerfile
    image: uch_backend
    command: sh -c "python3 manage.py makemigrations && 
                    python3 manage.py migrate --noinput && 
                    python3 manage.py collectstatic --noinput && 
                    gunicorn --config gunicorn_config.py myapp.wsgi:application"
    volumes:
      - "static_volume:/app/staticfiles"
      - "media_volume:/app/mediafiles"
    env_file:
      - .env.dev
    depends_on:
      - uch_db
      - uch_redis

  uch_db:
    container_name: uch_db
    image: postgres:15-alpine
    volumes:
      - "db_volume:/var/lib/postgresql/data/"
    env_file:
      - .env.dev

  uch_redis:
    container_name: uch_redis
    image: redis:7-alpine 

  uch_celery_worker:
    container_name: uch_celery_worker
    build:
      context: .
      dockerfile: Dockerfile
    image: uch_celery_worker
    command: sh -c "celery -A myapp worker -l info"
    volumes:
      - ".:/app"
    env_file:
      - .env.dev
    depends_on:
      - uch_db
      - uch_redis

  uch_nginx:
    container_name: uch_nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: uch_nginx
    ports:
      - 1337:80
    volumes:
      - "static_volume:/app/staticfiles"
      - "media_volume:/app/mediafiles"
    depends_on:
      - uch_backend

volumes:
  static_volume:
    name: static_volume
  media_volume:
    name: media_volume
  db_volume:
    name: db_volume