# Generated by Django 4.2.7 on 2024-02-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_topic',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
