# Generated by Django 4.2.7 on 2023-11-29 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('faculty_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('studyprogram_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('study_program_name', models.CharField(max_length=255)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.faculty')),
            ],
        ),
    ]
