# Generated by Django 4.2.7 on 2023-12-10 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('article_title', models.CharField(max_length=255)),
                ('article_body', models.TextField()),
                ('article_image', models.ImageField(blank=True, null=True, upload_to='article_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('booking_date', models.DateField()),
                ('booking_status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('active', 'Active'), ('done', 'Done'), ('rejected', 'Rejected')], default='created', max_length=30)),
                ('booking_needs', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingTime',
            fields=[
                ('bookingtime_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('committee_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('committee_name', models.CharField(max_length=255)),
                ('committee_position', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('faculty_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('room_name', models.CharField(max_length=100)),
                ('floor', models.IntegerField()),
                ('room_type', models.CharField(choices=[('meeting_room', 'Meeting Room')], max_length=30)),
                ('room_capacity', models.IntegerField()),
                ('room_description', models.TextField(blank=True, null=True)),
                ('room_rating', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('studyprogram_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('study_program_name', models.CharField(max_length=255)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('roomimage_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('room_image', models.ImageField(upload_to='room_images')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomFacility',
            fields=[
                ('roomfacility_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('facility_name', models.CharField(max_length=255)),
                ('facility_icon', models.ImageField(upload_to='facility_icons')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.room')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('rating_value', models.FloatField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingMember',
            fields=[
                ('bookingmember_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('student_id_number', models.CharField(max_length=30)),
                ('studyprogram', models.CharField(max_length=100)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='bookingtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bookingtime'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
