# Generated by Django 4.2.7 on 2024-02-29 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('article_type', models.CharField(max_length=30)),
                ('article_title', models.CharField(max_length=100)),
                ('article_body', models.TextField()),
                ('article_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('banner_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('banner_image', models.ImageField(upload_to='banner_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('booking_date', models.DateField()),
                ('booking_status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=30)),
                ('booking_needs', models.TextField(blank=True, null=True)),
                ('is_rated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingTime',
            fields=[
                ('bookingtime_id', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('committee_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('committee_name', models.CharField(max_length=255)),
                ('committee_position', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('faculty_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('room_name', models.CharField(max_length=100)),
                ('floor', models.IntegerField()),
                ('room_type', models.CharField(max_length=30)),
                ('room_capacity', models.IntegerField()),
                ('room_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_rating', models.FloatField(default=0.0)),
                ('total_raters', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('roomtype_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('room_type_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('studyprogram_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('study_program_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('roomimage_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('room_image', models.ImageField(upload_to='room_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomFacility',
            fields=[
                ('roomfacility_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('facility_name', models.CharField(max_length=255)),
                ('facility_icon', models.ImageField(upload_to='facility_icons')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.room')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('rating_value', models.FloatField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.booking')),
            ],
        ),
        migrations.CreateModel(
            name='BookingMember',
            fields=[
                ('bookingmember_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='bookingtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.bookingtime'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('articleimage_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('article_image', models.ImageField(upload_to='article_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.article')),
            ],
        ),
    ]
