# Generated by Django 4.2.7 on 2023-12-10 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmember',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='bookingmember',
            name='student_id_number',
        ),
        migrations.RemoveField(
            model_name='bookingmember',
            name='studyprogram',
        ),
        migrations.AddField(
            model_name='bookingmember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('active', 'Active'), ('done', 'Done'), ('rejected', 'Rejected')], default='initiated', max_length=30),
        ),
        migrations.AlterField(
            model_name='bookingmember',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.booking'),
        ),
    ]
