# Generated by Django 4.2.7 on 2023-11-29 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('article_title', models.CharField(max_length=255)),
                ('article_body', models.TextField()),
                ('article_image', models.ImageField(upload_to='article_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingTime',
            fields=[
                ('bookingtime_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('committee_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('committee_name', models.CharField(max_length=255)),
                ('committee_position', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('room_name', models.CharField(max_length=100)),
                ('floor', models.IntegerField()),
                ('room_type', models.CharField(max_length=30)),
                ('room_capacity', models.IntegerField()),
                ('room_description', models.TextField(blank=True, null=True)),
                ('room_rating', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('roomimage_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('room_image', models.ImageField(upload_to='room_images')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomFacility',
            fields=[
                ('roomfacility_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('facility_name', models.CharField(max_length=255)),
                ('facility_icon', models.ImageField(upload_to='facility_icons')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.room')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('rating_value', models.FloatField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('notification_title', models.CharField(max_length=255)),
                ('notification_body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('booking_date', models.DateField()),
                ('booking_duration', models.IntegerField()),
                ('booking_status', models.CharField(max_length=30)),
                ('booking_needs', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bookin_time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.bookingtime')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookerMember',
            fields=[
                ('bookermember_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('student_id_number', models.CharField(max_length=30)),
                ('studyprogram', models.CharField(max_length=100)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.booking')),
            ],
        ),
    ]
