# Generated by Django 4.2.7 on 2023-12-10 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_remove_bookingmember_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmember',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.booking'),
        ),
        migrations.AlterField(
            model_name='bookingmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
