# Generated by Django 4.2.7 on 2023-11-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_article_bookingtime_committee_room_roomimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('meeting_room', 'Meeting Room')], max_length=30),
        ),
    ]
