# Generated by Django 4.2.7 on 2023-11-29 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_duration',
        ),
        migrations.AddField(
            model_name='bookingtime',
            name='duration',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookin_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bookingtime'),
        ),
    ]
