# Generated by Django 4.2.7 on 2023-12-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_bookingmember_booking_alter_bookingmember_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_needs',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
