# Generated by Django 4.2.7 on 2024-02-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_booking_options_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=30),
        ),
    ]
