# Generated by Django 4.2.7 on 2024-02-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(default='Artikel', max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.CharField(max_length=100),
        ),
    ]
