# Generated by Django 4.2.7 on 2023-11-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_booking_booking_duration_bookingtime_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtime',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
