# Generated by Django 4.2.7 on 2023-12-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_booking_booking_needs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_needs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
