# Generated by Django 4.2.7 on 2024-02-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_article_article_link_article_article_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(max_length=30),
        ),
    ]
