# Generated by Django 4.2.7 on 2023-12-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_bookingtime_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
