# Generated by Django 4.2.7 on 2023-12-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_booking_booking_needs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtime',
            name='duration',
        ),
        migrations.AlterField(
            model_name='bookingtime',
            name='bookingtime_id',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, unique=True),
        ),
    ]
