# Generated by Django 4.2.7 on 2023-12-04 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_booking_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingMember',
            fields=[
                ('bookingmember_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('student_id_number', models.CharField(max_length=30)),
                ('studyprogram', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('done', 'Done'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
        migrations.DeleteModel(
            name='BookerMember',
        ),
        migrations.AddField(
            model_name='bookingmember',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.booking'),
        ),
    ]
