# Generated by Django 4.2.7 on 2023-12-14 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_bookingtime_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.bookingtime'),
        ),
    ]
