# Generated by Django 4.2.7 on 2024-02-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_article_article_image_articleimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('roomtype_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('room_type_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(max_length=30),
        ),
    ]
