# Generated by Django 4.2.7 on 2023-12-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_bookingmember_alter_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bookin_time',
            new_name='booking_time',
        ),
    ]
