# Generated by Django 4.2.7 on 2023-12-04 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_bookin_time_booking_booking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_time',
            new_name='bookingtime',
        ),
    ]
