# Generated by Django 4.2.7 on 2023-12-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_booking_time_booking_bookingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
