# Generated by Django 4.2.7 on 2023-12-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_booking_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('active', 'Active'), ('done', 'Done'), ('rejected', 'Rejected')], default='created', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
